# Generated by Django 6.0 on 2025-12-16 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_patient_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OcularAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior_segment', models.TextField(blank=True)),
                ('posterior_segment', models.TextField(blank=True)),
                ('glaucoma_suspect', models.BooleanField(default=False)),
                ('cataract_present', models.BooleanField(default=False)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocular_assessment', to='exams.examination')),
            ],
        ),
        migrations.CreateModel(
            name='Refraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere_right', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cylinder_right', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('axis_right', models.PositiveIntegerField(blank=True, null=True)),
                ('sphere_left', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cylinder_left', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('axis_left', models.PositiveIntegerField(blank=True, null=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refraction', to='exams.examination')),
            ],
        ),
        migrations.CreateModel(
            name='VisualAcuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_va_right', models.CharField(max_length=10)),
                ('distance_va_left', models.CharField(max_length=10)),
                ('near_va_right', models.CharField(blank=True, max_length=10)),
                ('near_va_left', models.CharField(blank=True, max_length=10)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_acuity', to='exams.examination')),
            ],
        ),
    ]
