# Generated by Django 6.0 on 2025-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
