# Generated by Django 6.0 on 2025-12-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
